-- 补齐 marketing_form_submission 审计字段 (幂等, 无实际 DDL)
-- 说明: 实体 MarketingFormSubmission 继承 BaseModel (含 createUser/updateUser/createTime/updateTime)。
-- 这些列已由 V1.12.0_1__marketing_form.sql 建表时一并创建, 本脚本不再重复 ADD,
-- 避免 Flyway 全量重跑时因重复列报 Error 1060 (Duplicate column name 'create_time')。
-- 本文件保留以维持版本号连续性, 内容为空操作。
